DAY = 1

TRANSACTION_DURATION = 5*DAY
FETCH_DATES_UNTIL_AMOUNT_DAYS = 10*DAY
AMOUNT_TO_INVEST_SINGLE_TRANSACTION = 100
POSITION_DETECTOR_MAX_RETRIES = 1000

WALLET_INITIAL_AMOUNT = 10000
AMOUNT_SINGLE_TRANSACTION = 100