pairs_slash = [
    'EUR/USD', 'EUR/CHF', 'EUR/GBP', 'EUR/JPY', 'EUR/AUD', 'USD/CAD', 'USD/CHF', 'USD/JPY',
    'USD/MXN', 'GBP/CHF', 'GBP/JPY', 'GBP/USD', 'AUD/JPY', 'AUD/USD', 'CHF/JPY', 'NZD/JPY',
    'NZD/USD', 'XAU/USD', 'EUR/CAD', 'AUD/CAD', 'CAD/JPY', 'EUR/NZD', 'GRX/EUR', 'NZD/CAD',
    'SGD/JPY', 'USD/HKD', 'USD/NOK', 'USD/TRY', 'XAU/AUD',
    'AUD/CHF', 'AUX/AUD', 'EUR/HUF', 'EUR/PLN', 'FRX/EUR', 'HKX/HKD', 'NZD/CHF', 'SPX/USD',
    'USD/HUF', 'USD/PLN', 'USD/ZAR', 'XAU/CHF', 'ZAR/JPY', 'BCO/USD', 'ETX/EUR', 'EUR/CZK',
    'EUR/SEK', 'GBP/AUD', 'GBP/NZD', 'JPX/JPY', 'UDX/USD', 'USD/CZK', 'USD/SEK', 'WTI/USD',
    'XAU/EUR', 'AUD/NZD', 'CAD/CHF', 'EUR/DKK', 'EUR/NOK', 'EUR/TRY', 'GBP/CAD', 'NSX/USD',
    'UKX/GBP', 'USD/DKK', 'USD/SGD', 'XAG/USD', 'XAU/GBP']

pairs_without_slash = (
    'EURUSD',
    'EURCHF',
    'EURGBP',
    'EURJPY',
    'EURAUD',
    'USDCAD',
    'USDCHF',
    'USDJPY',
    'USDMXN',
    'GBPCHF',
    'GBPJPY',
    'GBPUSD',
    'AUDJPY',
    'AUDUSD',
    'CHFJPY',
    'NZDJPY',
    'NZDUSD',
    'XAUUSD',
    'EURCAD',
    'AUDCAD',
    'CADJPY',
    'EURNZD',
    'GRXEUR',
    'NZDCAD',
    'SGDJPY',
    'USDHKD',
    'USDNOK',
    'USDTRY',
    'XAUAUD',
    'AUDCHF',
    'AUXAUD',
    'EURHUF',
    'EURPLN',
    'FRXEUR',
    'HKXHKD',
    'NZDCHF',
    'SPXUSD',
    'USDHUF',
    'USDPLN',
    'USDZAR',
    'XAUCHF',
    'ZARJPY',
    'BCOUSD',
    'ETXEUR',
    'EURCZK',
    'EURSEK',
    'GBPAUD',
    'GBPNZD',
    'JPXJPY',
    'UDXUSD',
    'USDCZK',
    'USDSEK',
    'WTIUSD',
    'XAUEUR',
    'AUDNZD',
    'CADCHF',
    'EURDKK',
    'EURNOK',
    'EURTRY',
    'GBPCAD',
    'NSXUSD',
    'UKXGBP',
    'USDDKK',
    'USDSGD',
    'XAGUSD',
    'XAUGBP'
)

pairs_without_slash_lower = [
    'eurusd',
    'eurchf',
    'eurgbp',
    'eurjpy',
    'euraud',
    'usdcad',
    'usdchf',
    'usdjpy',
    'usdmxn',
    'gbpchf',
    'gbpjpy',
    'gbpusd',
    'audjpy',
    'audusd',
    'chfjpy',
    'nzdjpy',
    'nzdusd',
    'xauusd',
    'eurcad',
    'audcad',
    'cadjpy',
    'eurnzd',
    'grxeur',
    'nzdcad',
    'sgdjpy',
    'usdhkd',
    'usdnok',
    'usdtry',
    'xauaud',
    'audchf',
    'auxaud',
    'eurhuf',
    'eurpln',
    'frxeur',
    'hkxhkd',
    'nzdchf',
    'spxusd',
    'usdhuf',
    'usdpln',
    'usdzar',
    'xauchf',
    'zarjpy',
    'bcousd',
    'etxeur',
    'eurczk',
    'eursek',
    'gbpaud',
    'gbpnzd',
    'jpxjpy',
    'udxusd',
    'usdczk',
    'usdsek',
    'wtiusd',
    'xaueur',
    'audnzd',
    'cadchf',
    'eurdkk',
    'eurnok',
    'eurtry',
    'gbpcad',
    'nsxusd',
    'ukxgbp',
    'usddkk',
    'usdsgd',
    'xagusd',
    'xaugbp'
]
